# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3e33f4d7550b0f0ce8811f81ec24cef2528a95e6ab77f03505b3b15053f83ae42d5552463e68b9fa0468e0be68e58eac5a27ffc12326e16df979884b284e077

test:
  secret_key_base: a4fcf720bc63892cec2f5e77652118c152e83131ca21bbb2e00d8b5fbf1127d05bc67e2b6d1c9d8b41f4f2cccf43360d79027ff72cf7741e0cd6795706387a29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
